import './Renderer.css.proxy.js';
/* src/sections/padding/Renderer.svelte generated by Svelte v3.24.0 */
import {
	SvelteComponent,
	append,
	attr,
	check_outros,
	create_component,
	destroy_component,
	destroy_each,
	detach,
	element,
	group_outros,
	init,
	insert,
	mount_component,
	safe_not_equal,
	set_data,
	space,
	text,
	transition_in,
	transition_out
} from "/tailwind-styleguide/web_modules/svelte/internal.js";

import ClassName from "../../components/ClassName.js";
import StyleguideSection from "../../components/StyleguideSection.js";

function get_each_context(ctx, list, i) {
	const child_ctx = ctx.slice();
	child_ctx[2] = list[i];
	return child_ctx;
}

// (59:6) <ClassName>
function create_default_slot_1(ctx) {
	let t0;
	let t1_value = /*spacing*/ ctx[2].name + "";
	let t1;

	return {
		c() {
			t0 = text(".p-");
			t1 = text(t1_value);
		},
		m(target, anchor) {
			insert(target, t0, anchor);
			insert(target, t1, anchor);
		},
		p(ctx, dirty) {
			if (dirty & /*meta*/ 1 && t1_value !== (t1_value = /*spacing*/ ctx[2].name + "")) set_data(t1, t1_value);
		},
		d(detaching) {
			if (detaching) detach(t0);
			if (detaching) detach(t1);
		}
	};
}

// (56:3) {#each meta.spacings as spacing}
function create_each_block(ctx) {
	let tr;
	let td0;
	let classname;
	let t0;
	let td1;
	let t1_value = /*spacing*/ ctx[2].value + "";
	let t1;
	let t2;
	let span;
	let t3_value = (/*spacing*/ ctx[2].unit ?? "") + "";
	let t3;
	let t4;
	let td2;
	let div;
	let div_style_value;
	let t5;
	let current;

	classname = new ClassName({
			props: {
				$$slots: { default: [create_default_slot_1] },
				$$scope: { ctx }
			}
		});

	return {
		c() {
			tr = element("tr");
			td0 = element("td");
			create_component(classname.$$.fragment);
			t0 = space();
			td1 = element("td");
			t1 = text(t1_value);
			t2 = space();
			span = element("span");
			t3 = text(t3_value);
			t4 = space();
			td2 = element("td");
			div = element("div");
			t5 = space();
			attr(td0, "class", "svelte-2nse5c");
			attr(span, "class", "unit svelte-2nse5c");
			attr(td1, "class", "measure svelte-2nse5c");
			attr(div, "style", div_style_value = `width: ${/*spacing*/ ctx[2].value}${/*spacing*/ ctx[2].unit ?? ""}`);
			attr(div, "class", "block svelte-2nse5c");
			attr(td2, "class", "svelte-2nse5c");
			attr(tr, "class", "svelte-2nse5c");
		},
		m(target, anchor) {
			insert(target, tr, anchor);
			append(tr, td0);
			mount_component(classname, td0, null);
			append(tr, t0);
			append(tr, td1);
			append(td1, t1);
			append(td1, t2);
			append(td1, span);
			append(span, t3);
			append(tr, t4);
			append(tr, td2);
			append(td2, div);
			append(tr, t5);
			current = true;
		},
		p(ctx, dirty) {
			const classname_changes = {};

			if (dirty & /*$$scope, meta*/ 33) {
				classname_changes.$$scope = { dirty, ctx };
			}

			classname.$set(classname_changes);
			if ((!current || dirty & /*meta*/ 1) && t1_value !== (t1_value = /*spacing*/ ctx[2].value + "")) set_data(t1, t1_value);
			if ((!current || dirty & /*meta*/ 1) && t3_value !== (t3_value = (/*spacing*/ ctx[2].unit ?? "") + "")) set_data(t3, t3_value);

			if (!current || dirty & /*meta*/ 1 && div_style_value !== (div_style_value = `width: ${/*spacing*/ ctx[2].value}${/*spacing*/ ctx[2].unit ?? ""}`)) {
				attr(div, "style", div_style_value);
			}
		},
		i(local) {
			if (current) return;
			transition_in(classname.$$.fragment, local);
			current = true;
		},
		o(local) {
			transition_out(classname.$$.fragment, local);
			current = false;
		},
		d(detaching) {
			if (detaching) detach(tr);
			destroy_component(classname);
		}
	};
}

// (46:0) <StyleguideSection name="Padding" description="Utilities for controlling an element's padding." variants={meta.variants}>
function create_default_slot(ctx) {
	let table;
	let thead;
	let t4;
	let tbody;
	let current;
	let each_value = /*meta*/ ctx[0].spacings;
	let each_blocks = [];

	for (let i = 0; i < each_value.length; i += 1) {
		each_blocks[i] = create_each_block(get_each_context(ctx, each_value, i));
	}

	const out = i => transition_out(each_blocks[i], 1, 1, () => {
		each_blocks[i] = null;
	});

	return {
		c() {
			table = element("table");
			thead = element("thead");

			thead.innerHTML = `<tr><td>Class</td> 
				<td class="measure svelte-2nse5c">Width</td> 
				<td></td></tr>`;

			t4 = space();
			tbody = element("tbody");

			for (let i = 0; i < each_blocks.length; i += 1) {
				each_blocks[i].c();
			}

			attr(thead, "class", "svelte-2nse5c");
			attr(tbody, "class", "svelte-2nse5c");
			attr(table, "class", "svelte-2nse5c");
		},
		m(target, anchor) {
			insert(target, table, anchor);
			append(table, thead);
			append(table, t4);
			append(table, tbody);

			for (let i = 0; i < each_blocks.length; i += 1) {
				each_blocks[i].m(tbody, null);
			}

			current = true;
		},
		p(ctx, dirty) {
			if (dirty & /*meta*/ 1) {
				each_value = /*meta*/ ctx[0].spacings;
				let i;

				for (i = 0; i < each_value.length; i += 1) {
					const child_ctx = get_each_context(ctx, each_value, i);

					if (each_blocks[i]) {
						each_blocks[i].p(child_ctx, dirty);
						transition_in(each_blocks[i], 1);
					} else {
						each_blocks[i] = create_each_block(child_ctx);
						each_blocks[i].c();
						transition_in(each_blocks[i], 1);
						each_blocks[i].m(tbody, null);
					}
				}

				group_outros();

				for (i = each_value.length; i < each_blocks.length; i += 1) {
					out(i);
				}

				check_outros();
			}
		},
		i(local) {
			if (current) return;

			for (let i = 0; i < each_value.length; i += 1) {
				transition_in(each_blocks[i]);
			}

			current = true;
		},
		o(local) {
			each_blocks = each_blocks.filter(Boolean);

			for (let i = 0; i < each_blocks.length; i += 1) {
				transition_out(each_blocks[i]);
			}

			current = false;
		},
		d(detaching) {
			if (detaching) detach(table);
			destroy_each(each_blocks, detaching);
		}
	};
}

function create_fragment(ctx) {
	let styleguidesection;
	let current;

	styleguidesection = new StyleguideSection({
			props: {
				name: "Padding",
				description: "Utilities for controlling an element's padding.",
				variants: /*meta*/ ctx[0].variants,
				$$slots: { default: [create_default_slot] },
				$$scope: { ctx }
			}
		});

	return {
		c() {
			create_component(styleguidesection.$$.fragment);
		},
		m(target, anchor) {
			mount_component(styleguidesection, target, anchor);
			current = true;
		},
		p(ctx, [dirty]) {
			const styleguidesection_changes = {};
			if (dirty & /*meta*/ 1) styleguidesection_changes.variants = /*meta*/ ctx[0].variants;

			if (dirty & /*$$scope, meta*/ 33) {
				styleguidesection_changes.$$scope = { dirty, ctx };
			}

			styleguidesection.$set(styleguidesection_changes);
		},
		i(local) {
			if (current) return;
			transition_in(styleguidesection.$$.fragment, local);
			current = true;
		},
		o(local) {
			transition_out(styleguidesection.$$.fragment, local);
			current = false;
		},
		d(detaching) {
			destroy_component(styleguidesection, detaching);
		}
	};
}

function instance($$self, $$props, $$invalidate) {
	let { meta } = $$props;
	let assignedClass;

	$$self.$set = $$props => {
		if ("meta" in $$props) $$invalidate(0, meta = $$props.meta);
	};

	return [meta];
}

class Renderer extends SvelteComponent {
	constructor(options) {
		super();
		init(this, options, instance, create_fragment, safe_not_equal, { meta: 0 });
	}
}

export default Renderer;