/* src/sections/borderRadius/Renderer.svelte generated by Svelte v3.24.0 */
import {
	SvelteComponent,
	create_component,
	destroy_component,
	init,
	mount_component,
	safe_not_equal,
	transition_in,
	transition_out
} from "/web_modules/svelte/internal.js";

import StyleguideSection from "../../components/StyleguideSection.js";
import Grid from "../../components/swatches/Grid.js";
import Swatch from "../../components/swatches/Swatch.js";

function create_default_slot_1(ctx) {
	let swatch;
	let current;

	swatch = new Swatch({
			props: {
				swatch: /*cn*/ ctx[2].name,
				filled: true,
				stroked: true
			}
		});

	return {
		c() {
			create_component(swatch.$$.fragment);
		},
		m(target, anchor) {
			mount_component(swatch, target, anchor);
			current = true;
		},
		p(ctx, dirty) {
			const swatch_changes = {};
			if (dirty & /*cn*/ 4) swatch_changes.swatch = /*cn*/ ctx[2].name;
			swatch.$set(swatch_changes);
		},
		i(local) {
			if (current) return;
			transition_in(swatch.$$.fragment, local);
			current = true;
		},
		o(local) {
			transition_out(swatch.$$.fragment, local);
			current = false;
		},
		d(detaching) {
			destroy_component(swatch, detaching);
		}
	};
}

// (10:0) <StyleguideSection name="Border Radius" description="For rounding off those sharp edges." variants={variants}>
function create_default_slot(ctx) {
	let grid;
	let current;

	grid = new Grid({
			props: {
				classes: /*classes*/ ctx[0],
				$$slots: {
					default: [
						create_default_slot_1,
						({ className: cn }) => ({ 2: cn }),
						({ className: cn }) => cn ? 4 : 0
					]
				},
				$$scope: { ctx }
			}
		});

	return {
		c() {
			create_component(grid.$$.fragment);
		},
		m(target, anchor) {
			mount_component(grid, target, anchor);
			current = true;
		},
		p(ctx, dirty) {
			const grid_changes = {};
			if (dirty & /*classes*/ 1) grid_changes.classes = /*classes*/ ctx[0];

			if (dirty & /*$$scope, cn*/ 12) {
				grid_changes.$$scope = { dirty, ctx };
			}

			grid.$set(grid_changes);
		},
		i(local) {
			if (current) return;
			transition_in(grid.$$.fragment, local);
			current = true;
		},
		o(local) {
			transition_out(grid.$$.fragment, local);
			current = false;
		},
		d(detaching) {
			destroy_component(grid, detaching);
		}
	};
}

function create_fragment(ctx) {
	let styleguidesection;
	let current;

	styleguidesection = new StyleguideSection({
			props: {
				name: "Border Radius",
				description: "For rounding off those sharp edges.",
				variants: /*variants*/ ctx[1],
				$$slots: { default: [create_default_slot] },
				$$scope: { ctx }
			}
		});

	return {
		c() {
			create_component(styleguidesection.$$.fragment);
		},
		m(target, anchor) {
			mount_component(styleguidesection, target, anchor);
			current = true;
		},
		p(ctx, [dirty]) {
			const styleguidesection_changes = {};
			if (dirty & /*variants*/ 2) styleguidesection_changes.variants = /*variants*/ ctx[1];

			if (dirty & /*$$scope, classes*/ 9) {
				styleguidesection_changes.$$scope = { dirty, ctx };
			}

			styleguidesection.$set(styleguidesection_changes);
		},
		i(local) {
			if (current) return;
			transition_in(styleguidesection.$$.fragment, local);
			current = true;
		},
		o(local) {
			transition_out(styleguidesection.$$.fragment, local);
			current = false;
		},
		d(detaching) {
			destroy_component(styleguidesection, detaching);
		}
	};
}

function instance($$self, $$props, $$invalidate) {
	let { classes } = $$props;
	let { variants } = $$props;

	$$self.$set = $$props => {
		if ("classes" in $$props) $$invalidate(0, classes = $$props.classes);
		if ("variants" in $$props) $$invalidate(1, variants = $$props.variants);
	};

	return [classes, variants];
}

class Renderer extends SvelteComponent {
	constructor(options) {
		super();
		init(this, options, instance, create_fragment, safe_not_equal, { classes: 0, variants: 1 });
	}
}

export default Renderer;